# Generated by Django 4.0.1 on 2022-01-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_mail_remove_company_email_company_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='footer_picture',
            field=models.FileField(blank=True, null=True, upload_to='Configuration_file'),
        ),
    ]
