# Generated by Django 4.0.1 on 2022-01-07 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0002_reference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produit',
        ),
        migrations.DeleteModel(
            name='Typeproduit',
        ),
    ]
