# Generated by Django 4.0.1 on 2022-01-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0003_delete_produit_delete_typeproduit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='annee',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='commande',
            name='telephone',
            field=models.CharField(max_length=255),
        ),
    ]
