# Generated by Django 4.0.1 on 2022-01-08 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0004_alter_commande_annee_alter_commande_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
            },
        ),
        migrations.AlterField(
            model_name='piece',
            name='marque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marque_piece', to='siteweb.marque'),
        ),
    ]
