# Generated by Django 4.0.1 on 2022-01-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0005_marque_alter_piece_marque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='annee',
            field=models.CharField(max_length=255),
        ),
    ]
