# Generated by Django 4.0.1 on 2022-01-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0006_alter_piece_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseaux',
            name='lien',
            field=models.CharField(max_length=255),
        ),
    ]
